services:
  # postgresql://test:test@localhost:5432/test
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
# volumes:
#   pgdata:
