name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flags:
          - "--features arrow-54 json"
          - "--features arrow-55 json"
          - "--features arrow-56 json"
          - "--features postgres-core"
          - "--features sqlx"
    steps:
      - uses: actions/checkout@v5
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Test feature ${matrix.flags}
        run: cargo test ${matrix.flags}
